name: Angular to WebApp

on: [push]

env:
  AZURE_WEBAPP_NAME: hiitoangular    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/hiitoangular'      # set this to the path to your web app project.
  NODE_VERSION: '12.x' 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build -- --prod  
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: hiitoangular
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
